/* Central Texas Water Ledger map: reads ../dist/water-state.json and draws stations, wells, lakes and EAA sites.
   Context only. Every card says what was measured, when, and how it compares with the same station's record. */
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LAKE_LL={austin:[30.325,-97.820],travis:[30.392,-97.906],buchanan:[30.790,-98.420],inks:[30.737,-98.370],'lyndon-b-johnson':[30.556,-98.370],'marble-falls':[30.567,-98.270],canyon:[29.873,-98.198],medina:[29.545,-98.930],georgetown:[30.670,-97.730],granger:[30.700,-97.330]};
let bundle=null,map=null,layers={stations:[],wells:[],lakes:[],eaa:[]};
const on={stations:true,wells:false,lakes:true,eaa:false};
function fmt(s){ if(!s) return 'not recorded'; const d=new Date(s); return Number.isNaN(d.getTime())?String(s):d.toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' CT'; }
function chg(v,unit){ return v==null?'not enough record':`${v>0?'+':''}${v} ${unit}`; }
function pin(kind,stale,label){ return L.divIcon({className:'',html:`<span class="pin ${kind}${stale?' stale':''}" title="${esc(label)}"></span>`,iconSize:[16,16],iconAnchor:[8,8]}); }
function clear(){ Object.values(layers).flat().forEach(m=>m.remove()); layers={stations:[],wells:[],lakes:[],eaa:[]}; }
function render(){ if(!bundle||!map) return; clear();
  if(on.stations) for(const [id,s] of Object.entries(bundle.stations)){ if(s.lat==null) continue; const q=s.latest['00060']||s.latest['00065']||Object.values(s.latest)[0]; const stale=!q||!q.fresh_within_1h;
    const m=L.marker([s.lat,s.lon],{icon:pin('station',stale,s.name||id)}); m.bindTooltip(`${esc(s.name||id)}${q?` · ${esc(q.value)} ${esc(q.unit)}`:''}`); m.on('click',()=>showStation(id,s)); m.addTo(map); layers.stations.push(m); }
  if(on.wells) for(const [id,w] of Object.entries(bundle.wells)){ if(!w.latest) continue; const m=L.marker([w.lat,w.lon],{icon:pin('well',w.data_health!=='fresh',`${w.aquifer} well ${id}`)}); m.bindTooltip(`Well ${esc(id)} · ${esc(w.aquifer)} · ${esc(w.latest.level_ft_bls)} ft below surface`); m.on('click',()=>showWell(id,w)); m.addTo(map); layers.wells.push(m); }
  if(on.lakes) for(const [slug,l] of Object.entries(bundle.lakes)){ const ll=LAKE_LL[slug]; if(!ll||!l.latest) continue; const m=L.marker(ll,{icon:pin('lake',l.data_health!=='fresh',l.name)}); m.bindTooltip(`${esc(l.name)} · ${esc(l.latest.percent_full)}% full`); m.on('click',()=>showLake(slug,l)); m.addTo(map); layers.lakes.push(m); }
  if(on.eaa&&bundle.eaa){ for(const [id,w] of Object.entries(bundle.eaa.wells)){ if(w.latitude==null) continue; const m=L.marker([w.latitude,w.longitude],{icon:pin('eaa',w.data_health!=='fresh',w.siteName)}); m.bindTooltip(`EAA well ${esc(id)} · ${esc(w.siteName)}`); m.on('click',()=>showEaaWell(id,w)); m.addTo(map); layers.eaa.push(m); }
    for(const [id,g] of Object.entries(bundle.eaa.rain_gauges)){ if(g.latitude==null) continue; const m=L.marker([g.latitude,g.longitude],{icon:pin('eaa',g.data_health!=='fresh',g.siteName)}); m.bindTooltip(`Rain gauge ${esc(id)} · ${esc(g.siteName)}`); m.on('click',()=>showRain(id,g)); m.addTo(map); layers.eaa.push(m); } }
}
function card(html){ $('#detail').innerHTML=html; }
function showStation(id,s){ const rows=Object.entries(s.latest).map(([p,v])=>`<div><b>${esc(v.unit==='ft^3/s'?'Flow':p==='00065'?'Gage height':p)}:</b> ${esc(v.value)} ${esc(v.unit)} · ${esc(fmt(v.observed_at))} ${v.fresh_within_1h?'':'<span class="muted">· not within an hour of the bundle</span>'}</div>`).join('')||'<div class="muted">No reading in the latest capture.</div>';
  const c=s.context; const ctx=c?`<p>${esc(c.narrative||'')}</p>`:'<p class="muted">No history-tier context for this station (current readings only).</p>';
  const th=s.thresholds?`<div><b>Station's own event thresholds:</b> high ${esc(s.thresholds.high)}, low ${esc(s.thresholds.low)} (${esc(s.thresholds.unit)}); descriptive, not a swim or flood line.</div>`:'';
  card(`<p class="eyebrow">USGS ${esc(s.kind||'site')} · ${esc(id)} · ${esc(s.county||'')}</p><h2>${esc(s.name||id)}</h2><span class="badge">${esc(s.tier)}</span>
    <div class="fact"><h3>Measured</h3>${rows}</div><div class="fact"><h3>Context · this station's own record</h3>${ctx}${th}</div>
    <p><a href="${esc(s.source)}" target="_blank" rel="noreferrer">USGS station page ↗</a></p>`); }
function showWell(id,w){ card(`<p class="eyebrow">TWDB well · state well ${esc(id)} · ${esc(w.county||'')} County</p><h2>${esc(w.aquifer||'Aquifer not listed')}</h2><span class="badge">${esc(w.data_health)}</span>${w.index?'<span class="badge">full record kept</span>':''}
    <div class="fact"><h3>Measured in the well</h3><div><b>Latest:</b> ${esc(w.latest.level_ft_bls)} ft below land surface · ${esc(w.latest.date)}</div><div><b>7 days:</b> ${esc(chg(w.change_7d_ft,'ft'))} · <b>30 days:</b> ${esc(chg(w.change_30d_ft,'ft'))}</div><div><b>Direction:</b> ${esc(w.direction||'not established')}</div><div><b>Against 13 months:</b> ${w.percentile_13mo!=null?esc(w.percentile_13mo+'th percentile (higher = deeper water table)'):esc(w.percentile_note||'withheld')}</div><div class="muted">${esc(w.record_days_on_file)} days on file · ${esc(w.entity||'')}</div></div>
    <p class="muted">A larger number is a lower water table. Context for springs and creeks fed by this aquifer; not a verdict.</p><p><a href="${esc(w.source)}" target="_blank" rel="noreferrer">Water Data for Texas ↗</a></p>`); }
function showLake(slug,l){ card(`<p class="eyebrow">TWDB reservoir · ${esc(slug)}</p><h2>${esc(l.name)}</h2><span class="badge">${esc(l.data_health)}</span>
    <div class="fact"><h3>Measured</h3><div><b>Elevation:</b> ${esc(l.latest.elevation_ft)} ft above mean sea level · ${esc(l.latest.date)}</div><div><b>Percent full:</b> ${esc(l.latest.percent_full)}% of conservation capacity</div><div><b>7 days:</b> ${esc(chg(l.change_7d_ft,'ft'))} · <b>30 days:</b> ${esc(chg(l.change_30d_ft,'ft'))}</div><div><b>Against 13 months:</b> ${l.percentile_13mo!=null?esc(l.percentile_13mo+'th percentile of daily elevation'):'withheld'}</div><div class="muted">${esc(l.record_days_on_file)} days on file from ${esc(l.first_date_on_file)}</div></div>
    <p class="muted">Managed storage relayed by TWDB; context for the lake and the river below the dam.</p><p><a href="${esc(l.source)}" target="_blank" rel="noreferrer">Water Data for Texas ↗</a></p>`); }
function showEaaWell(id,w){ const lt=w.latest?`<div><b>Latest:</b> ${esc(w.latest.elevation_ft_amsl)} ft above mean sea level · ${esc(w.latest.date)}</div><div><b>7 days:</b> ${esc(chg(w.change_7d_ft,'ft'))} · <b>30 days:</b> ${esc(chg(w.change_30d_ft,'ft'))}</div><div><b>Against 13 months:</b> ${w.percentile_13mo!=null?esc(w.percentile_13mo+'th percentile'):'withheld'}</div>`:'<div class="muted">No level on file (the EAA server has not answered for this site yet).</div>';
  card(`<p class="eyebrow">Edwards Aquifer Authority well · ${esc(id)} · ${esc(w.county||'')}</p><h2>${esc(w.siteName)}</h2><span class="badge">${esc(w.data_health)}</span><span class="badge">${esc(w.aquiferZone||'')}</span><div class="fact"><h3>Measured</h3>${lt}</div><p class="muted">Higher elevation means a higher water table.</p><p><a href="${esc(w.source)}" target="_blank" rel="noreferrer">EAA site page ↗</a></p>`); }
function showRain(id,g){ const t=g.latest?`<div><b>Last day:</b> ${esc(g.last_1d.inches)} in · <b>3 days:</b> ${esc(g.last_3d.inches)} in · <b>7 days:</b> ${esc(g.last_7d.inches)} in (${esc(g.last_7d.days_reported)} days reported) · <b>30 days:</b> ${esc(g.last_30d.inches)} in</div><div class="muted">latest ${esc(g.latest.date)}</div>`:'<div class="muted">No reading on file yet.</div>';
  card(`<p class="eyebrow">EAA rain gauge · ${esc(id)} · ${esc(g.county||'')}</p><h2>${esc(g.siteName)}</h2><span class="badge">${esc(g.data_health)}</span><div class="fact"><h3>Measured</h3>${t}</div><p class="muted">A missing day is unreported, never zero.</p><p><a href="${esc(g.source)}" target="_blank" rel="noreferrer">EAA site page ↗</a></p>`); }
function boot(){ map=L.map('map',{zoomControl:true}).setView([30.05,-98.6],8); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);
  for(const k of ['stations','wells','lakes','eaa']){ const el=$('#l-'+k); el.checked=on[k]; el.addEventListener('change',()=>{on[k]=el.checked; render();}); }
  fetch('../dist/water-state.json').then(r=>r.json()).then(b=>{ bundle=b; $('#bundle-meta').textContent=`Bundle ${b.schema_version} generated ${fmt(b.generated_at)} · ${b.counts.stations} stations, ${b.counts.wells} wells, ${b.counts.lakes} lakes · missing inputs: ${(b.missing_inputs||[]).join(', ')||'none'}`; render(); }).catch(e=>{ $('#bundle-meta').textContent='Could not load dist/water-state.json: '+e; }); }
document.addEventListener('DOMContentLoaded',boot);
