/* Central Texas Water Ledger map: reads ../dist/water-state.json and draws stations, wells, lakes and EAA sites.
   Context only. Every card says what was measured, when, and how it compares with the same station's record. */
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LAKE_LL={austin:[30.325,-97.820],travis:[30.392,-97.906],buchanan:[30.790,-98.420],inks:[30.737,-98.370],'lyndon-b-johnson':[30.556,-98.370],'marble-falls':[30.567,-98.270],canyon:[29.873,-98.198],medina:[29.545,-98.930],georgetown:[30.670,-97.730],granger:[30.700,-97.330]};
let bundle=null,map=null,layers={stations:[],wells:[],lakes:[],eaa:[],hydromet:[],storm:[]};
const on={stations:true,wells:false,lakes:true,eaa:false,hydromet:false,storm:false};
function fmt(s){ if(!s) return 'not recorded'; const d=new Date(s); return Number.isNaN(d.getTime())?String(s):d.toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' CT'; }
function chg(v,unit){ return v==null?'not enough record':`${v>0?'+':''}${v} ${unit}`; }
function pin(kind,stale,label){ return L.divIcon({className:'',html:`<span class="pin ${kind}${stale?' stale':''}" title="${esc(label)}"></span>`,iconSize:[16,16],iconAnchor:[8,8]}); }
function clear(){ Object.values(layers).flat().forEach(m=>m.remove()); layers={stations:[],wells:[],lakes:[],eaa:[],hydromet:[],storm:[]}; }
function render(){ if(!bundle||!map) return; clear(); renderStorm();
  if(on.stations) for(const [id,s] of Object.entries(bundle.stations)){ if(s.lat==null) continue; const q=s.latest['00060']||s.latest['00065']||Object.values(s.latest)[0]; const stale=!q||!q.fresh_within_1h;
    const m=L.marker([s.lat,s.lon],{icon:pin('station',stale,s.name||id)}); m.bindTooltip(`${esc(s.name||id)}${q?` · ${esc(q.value)} ${esc(q.unit)}`:''}`); m.on('click',()=>showStation(id,s)); m.addTo(map); layers.stations.push(m); }
  if(on.wells) for(const [id,w] of Object.entries(bundle.wells)){ if(!w.latest) continue; const m=L.marker([w.lat,w.lon],{icon:pin('well',w.data_health!=='fresh',`${w.aquifer} well ${id}`)}); m.bindTooltip(`Well ${esc(id)} · ${esc(w.aquifer)} · ${esc(w.latest.level_ft_bls)} ft below surface`); m.on('click',()=>showWell(id,w)); m.addTo(map); layers.wells.push(m); }
  if(on.lakes) for(const [slug,l] of Object.entries(bundle.lakes)){ const ll=LAKE_LL[slug]; if(!ll||!l.latest) continue; const m=L.marker(ll,{icon:pin('lake',l.data_health!=='fresh',l.name)}); m.bindTooltip(`${esc(l.name)} · ${esc(l.latest.percent_full)}% full`); m.on('click',()=>showLake(slug,l)); m.addTo(map); layers.lakes.push(m); }
  if(on.eaa&&bundle.eaa){ for(const [id,w] of Object.entries(bundle.eaa.wells)){ if(w.latitude==null) continue; const m=L.marker([w.latitude,w.longitude],{icon:pin('eaa',w.data_health!=='fresh',w.siteName)}); m.bindTooltip(`EAA well ${esc(id)} · ${esc(w.siteName)}`); m.on('click',()=>showEaaWell(id,w)); m.addTo(map); layers.eaa.push(m); }
    for(const [id,g] of Object.entries(bundle.eaa.rain_gauges)){ if(g.latitude==null) continue; const m=L.marker([g.latitude,g.longitude],{icon:pin('eaa',g.data_health!=='fresh',g.siteName)}); m.bindTooltip(`Rain gauge ${esc(id)} · ${esc(g.siteName)}`); m.on('click',()=>showRain(id,g)); m.addTo(map); layers.eaa.push(m); } }
  if(on.hydromet&&bundle.hydromet) for(const [key,s] of Object.entries(bundle.hydromet.sites)){ if(s.lat==null||s.agency==='USGS') continue; const q=s.flow_cfs!=null?`${s.flow_cfs} cfs`:s.stage_ft!=null?`stage ${s.stage_ft} ft`:s.head_ft!=null?`head ${s.head_ft} ft`:s.rain_in&&s.rain_in['1Day']!=null?`${s.rain_in['1Day']} in / 24 h`:null;
    const m=L.marker([s.lat,s.lon],{icon:pin('hydromet',!s.fresh_within_1h,s.name)}); m.bindTooltip(`${esc(s.agency)} ${esc(s.site)} · ${esc(s.name)}${q?` · ${esc(q)}`:''}`); m.on('click',()=>showHydromet(key,s)); m.addTo(map); layers.hydromet.push(m); }
}
function card(html){ $('#detail').innerHTML=html; }
function showHydromet(key,s){ const rows=[]; if(s.flow_cfs!=null) rows.push(`<div><b>Flow:</b> ${esc(s.flow_cfs)} cfs</div>`); if(s.stage_ft!=null) rows.push(`<div><b>Stage:</b> ${esc(s.stage_ft)} ft${s.flood_stage_ft!=null?` <span class="muted">(NWS flood stage ${esc(s.flood_stage_ft)} ft)</span>`:''}</div>`);
  if(s.head_ft!=null) rows.push(`<div><b>Headwater:</b> ${esc(s.head_ft)} ft msl${s.tail_ft!=null?` · <b>tailwater:</b> ${esc(s.tail_ft)} ft`:''}</div>`); if(s.water_temp_f!=null) rows.push(`<div><b>Water temperature:</b> ${esc(s.water_temp_f)} °F</div>`);
  const r=s.rain_in||{}; if(r['1Day']!=null||r['1Week']!=null) rows.push(`<div><b>Rain:</b> ${esc(r['1Hour']??'–')} in last hour · ${esc(r['1Day']??'–')} in / 24 h · ${esc(r['3Days']??'–')} in / 3 days · ${esc(r['1Week']??'–')} in / week · ${esc(r['30Days']??'–')} in / 30 days</div>`);
  const hist=(s.history||[]).length?`<div><b>History on file:</b> ${esc(s.history.join(', '))} (see <code>data/captures/hydromet/</code>)</div>`:'<div class="muted">Live readings only; no history pulled for this site yet.</div>';
  card(`<p class="eyebrow">${esc(s.agency==='COA'?'City of Austin flood-warning gauge':'LCRA Hydromet gauge')} · site ${esc(s.site)} · ${esc(s.site_type)}${s.creek?` · ${esc(s.creek)}`:''}</p><h2>${esc(s.name)}</h2><span class="badge">${s.fresh_within_1h?'fresh':'not within an hour of the bundle'}</span>
  ${rows.join('')||'<div class="muted">No numeric reading in the latest capture.</div>'}<div class="muted">reported ${esc(fmt(s.observed_at))}</div>${hist}
  <p class="muted">A reading at the gauge, as the operator publishes it. A City gauge's 0.00 cfs is the City's value, not a verdict on the creek downstream. Source: <a href="https://hydromet.lcra.org/" target="_blank" rel="noopener">hydromet.lcra.org</a>.</p>`); }
function showStation(id,s){ const rows=Object.entries(s.latest).map(([p,v])=>`<div><b>${esc(v.unit==='ft^3/s'?'Flow':p==='00065'?'Gage height':p)}:</b> ${esc(v.value)} ${esc(v.unit)} · ${esc(fmt(v.observed_at))} ${v.fresh_within_1h?'':'<span class="muted">· not within an hour of the bundle</span>'}</div>`).join('')||'<div class="muted">No reading in the latest capture.</div>';
  const c=s.context; const ctx=c?`<p>${esc(c.narrative||'')}</p>`:'<p class="muted">No history-tier context for this station (current readings only).</p>';
  const th=s.thresholds?`<div><b>Station's own event thresholds:</b> high ${esc(s.thresholds.high)}, low ${esc(s.thresholds.low)} (${esc(s.thresholds.unit)}); descriptive, not a swim or flood line.</div>`:'';
  card(`<p class="eyebrow">USGS ${esc(s.kind||'site')} · ${esc(id)} · ${esc(s.county||'')}</p><h2>${esc(s.name||id)}</h2><span class="badge">${esc(s.tier)}</span>
    <div class="fact"><h3>Measured</h3>${rows}</div><div class="fact"><h3>Context · this station's own record</h3>${ctx}${th}</div>
    <p><a href="${esc(s.source)}" target="_blank" rel="noreferrer">USGS station page ↗</a></p>`); }
function showWell(id,w){ card(`<p class="eyebrow">TWDB well · state well ${esc(id)} · ${esc(w.county||'')} County</p><h2>${esc(w.aquifer||'Aquifer not listed')}</h2><span class="badge">${esc(w.data_health)}</span>${w.index?'<span class="badge">full record kept</span>':''}
    <div class="fact"><h3>Measured in the well</h3><div><b>Latest:</b> ${esc(w.latest.level_ft_bls)} ft below land surface · ${esc(w.latest.date)}</div><div><b>7 days:</b> ${esc(chg(w.change_7d_ft,'ft'))} · <b>30 days:</b> ${esc(chg(w.change_30d_ft,'ft'))}</div><div><b>Direction:</b> ${esc(w.direction||'not established')}</div><div><b>Against 13 months:</b> ${w.percentile_13mo!=null?esc(w.percentile_13mo+'th percentile (higher = deeper water table)'):esc(w.percentile_note||'withheld')}</div><div class="muted">${esc(w.record_days_on_file)} days on file · ${esc(w.entity||'')}</div></div>
    <p class="muted">A larger number is a lower water table. Context for springs and creeks fed by this aquifer; not a verdict.</p><p><a href="${esc(w.source)}" target="_blank" rel="noreferrer">Water Data for Texas ↗</a></p>`); }
function showLake(slug,l){ card(`<p class="eyebrow">TWDB reservoir · ${esc(slug)}</p><h2>${esc(l.name)}</h2><span class="badge">${esc(l.data_health)}</span>
    <div class="fact"><h3>Measured</h3><div><b>Elevation:</b> ${esc(l.latest.elevation_ft)} ft above mean sea level · ${esc(l.latest.date)}</div><div><b>Percent full:</b> ${esc(l.latest.percent_full)}% of conservation capacity</div><div><b>7 days:</b> ${esc(chg(l.change_7d_ft,'ft'))} · <b>30 days:</b> ${esc(chg(l.change_30d_ft,'ft'))}</div><div><b>Against 13 months:</b> ${l.percentile_13mo!=null?esc(l.percentile_13mo+'th percentile of daily elevation'):'withheld'}</div><div class="muted">${esc(l.record_days_on_file)} days on file from ${esc(l.first_date_on_file)}</div></div>
    <p class="muted">Managed storage relayed by TWDB; context for the lake and the river below the dam.</p><p><a href="${esc(l.source)}" target="_blank" rel="noreferrer">Water Data for Texas ↗</a></p>`); }
function showEaaWell(id,w){ const lt=w.latest?`<div><b>Latest:</b> ${esc(w.latest.elevation_ft_amsl)} ft above mean sea level · ${esc(w.latest.date)}</div><div><b>7 days:</b> ${esc(chg(w.change_7d_ft,'ft'))} · <b>30 days:</b> ${esc(chg(w.change_30d_ft,'ft'))}</div><div><b>Against 13 months:</b> ${w.percentile_13mo!=null?esc(w.percentile_13mo+'th percentile'):'withheld'}</div>`:'<div class="muted">No level on file (the EAA server has not answered for this site yet).</div>';
  card(`<p class="eyebrow">Edwards Aquifer Authority well · ${esc(id)} · ${esc(w.county||'')}</p><h2>${esc(w.siteName)}</h2><span class="badge">${esc(w.data_health)}</span><span class="badge">${esc(w.aquiferZone||'')}</span><div class="fact"><h3>Measured</h3>${lt}</div><p class="muted">Higher elevation means a higher water table.</p><p><a href="${esc(w.source)}" target="_blank" rel="noreferrer">EAA site page ↗</a></p>`); }
function showRain(id,g){ const t=g.latest?`<div><b>Last day:</b> ${esc(g.last_1d.inches)} in · <b>3 days:</b> ${esc(g.last_3d.inches)} in · <b>7 days:</b> ${esc(g.last_7d.inches)} in (${esc(g.last_7d.days_reported)} days reported) · <b>30 days:</b> ${esc(g.last_30d.inches)} in</div><div class="muted">latest ${esc(g.latest.date)}</div>`:'<div class="muted">No reading on file yet.</div>';
  card(`<p class="eyebrow">EAA rain gauge · ${esc(id)} · ${esc(g.county||'')}</p><h2>${esc(g.siteName)}</h2><span class="badge">${esc(g.data_health)}</span><div class="fact"><h3>Measured</h3>${t}</div><p class="muted">A missing day is unreported, never zero.</p><p><a href="${esc(g.source)}" target="_blank" rel="noreferrer">EAA site page ↗</a></p>`); }
/* Base map: the USGS National Map (public domain; topo with the National Hydrography drawn) is the default because this is a
   map of water gauges and the hydrography is the point. A plain light base (CARTO, free with attribution) is the alternate for
   dense marker views. OpenStreetMap's own tile server is kept out of production use per its tile-usage policy. */
const BASES={
  'USGS topo + hydro':()=>L.layerGroup([
    L.tileLayer('https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:'USGS The National Map: USGS Topo (public domain)'}),
    L.tileLayer('https://basemap.nationalmap.gov/arcgis/rest/services/USGSHydroCached/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,opacity:.85,attribution:'USGS National Hydrography'})]),
  'USGS imagery + topo':()=>L.tileLayer('https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:'USGS The National Map: Imagery Topo (public domain)'}),
  'Light (CARTO)':()=>L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,subdomains:'abcd',attribution:'© OpenStreetMap contributors © CARTO'})
};
function boot(){ map=L.map('map',{zoomControl:true}).setView([30.05,-98.6],8);
  const baseLayers=Object.fromEntries(Object.entries(BASES).map(([k,f])=>[k,f()])); baseLayers['USGS topo + hydro'].addTo(map); L.control.layers(baseLayers,null,{position:'topright',collapsed:true}).addTo(map);
  for(const k of ['stations','wells','lakes','eaa','hydromet','storm']){ const el=$('#l-'+k); el.checked=on[k]; el.addEventListener('change',()=>{on[k]=el.checked; render();}); }
  fetch('../dist/water-state.json',{cache:'no-cache'}).then(r=>r.json()).then(b=>{ bundle=b; initStorm(); $('#bundle-meta').textContent=`Bundle ${b.schema_version} generated ${fmt(b.generated_at)} · ${b.counts.stations} stations, ${b.counts.wells} wells, ${b.counts.lakes} lakes · missing inputs: ${(b.missing_inputs||[]).join(', ')||'none'}`; render(); }).catch(e=>{ $('#bundle-meta').textContent='Could not load dist/water-state.json: '+e; }); }
document.addEventListener('DOMContentLoaded',boot);

/* Storm measurements use their own palette and card functions. */
let stormId=null;
const STORM_COLORS={'no response':'#a6a9b3',flash:'#8264ab',sustained:'#356b9a',modest:'#515d76'};
const stormTime=s=>!s?'not recorded':/^\d{4}-\d{2}-\d{2}$/.test(s)?s+' (daily record)':s.replace('T',' ').replace('+00:00','Z').replace('Z',' UTC');
const sn=v=>v==null?'not recorded':Number(v).toLocaleString('en-US',{maximumFractionDigits:3});
const timed=(v,t,u)=>v==null?'not recorded':`${sn(v)} ${u} at ${stormTime(t)}`;
function initStorm(){ const select=$('#storm-select'); const ids=Object.keys(bundle.storm_delta?.storms||{}).sort().reverse();
  select.innerHTML=ids.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join(''); stormId=ids[0]||null;
  select.addEventListener('change',()=>{stormId=select.value;render();}); }
function selectedStorm(){return bundle?.storm_delta?.storms?.[stormId];}
function stormSymbol(svg,size=28){return L.divIcon({className:'',html:`<svg class="storm-icon" width="${size}" height="${size}" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${svg}</svg>`,iconSize:[size,size],iconAnchor:[size/2,size/2]});}
function stormMarker(ll,icon,tooltip,click){if(ll.some(x=>x==null)) return;const m=L.marker(ll,{icon,title:tooltip,alt:tooltip});m.bindTooltip(esc(tooltip));m.on('click',click);m.addTo(map);layers.storm.push(m);}
function flowRankText(s){const p=s.peak_rank,a=s.annual_rank;
  if(p) return p.rank>p.years?`Peak is below every annual instantaneous maximum in the ${p.years} saved water years (${p.record_first_year||'record start not supplied'}–${p.record_last_year||'record end not supplied'}).`:`Peak ranks ${p.rank} against ${p.years} saved annual instantaneous maxima; record ${timed(p.record_peak_cfs,p.record_date,'cfs')}.`;
  if(a) return a.rank>a.years?`Peak is below every annual daily maximum in ${a.years} saved calendar years; comparison is against daily means.`:`Peak ranks ${a.rank} against ${a.years} calendar-year maxima of daily means; record ${sn(a.record_daily_mean)} cfs in ${a.record_year}.`;
  return 'No historical rank on file.';}
function flowLine(s){return `${timed(s.start_cfs,s.start_at,'cfs')} → ${timed(s.peak_cfs,s.peak_at,'cfs')} → ${timed(s.now_cfs,s.now_at,'cfs')}`;}
function renderStorm(){const panel=$('#storm-panel');panel.hidden=!on.storm;if(!on.storm)return;const s=selectedStorm();if(!s){$('#storm-summary').textContent='No detected storm record is published.';return;}
  const w=s.window;$('#storm-summary').textContent=`Window: ${stormTime(w.t0)} to ${w.t1?stormTime(w.t1):'still open at '+stormTime(s.computed_through)}. Trigger: at least 20% of reporting rain gauges reached 1 inch in the previous day, or a flow gauge crossed its own event threshold. Start is 24 hours before the first trigger; end is 72 hours after observed recession, capped at 10 days. These boundaries are rules, not observations.`;
  for(const [id,r] of Object.entries(s.rain||{})){const missing=r.inches_window==null, radius=missing?9:4+18*Math.sqrt(Math.min(8,Math.max(0,r.inches_window))/8); const shade=missing?'none':`hsl(211 55% ${85-50*Math.min(8,r.inches_window)/8}%)`;
    stormMarker([r.lat,r.lon],stormSymbol(`<circle data-missing="${missing}" cx="24" cy="24" r="${radius}" fill="${shade}" stroke="#294e76" stroke-width="1.5"/>`,48),`${r.name}: ${timed(r.inches_window,r.observed_at,'in; rolling '+(r.accumulation_field||'unknown'))}`,()=>showStormRain(id,r));}
  for(const [id,f] of Object.entries(s.flow||{})){const size=f.ratio==null?20:18+Math.min(22,5*Math.log10(1+Math.max(0,f.ratio)));const fill=STORM_COLORS[f.response_class]||'none';
    stormMarker([f.lat,f.lon],stormSymbol(`${f.crossed?'<circle cx="24" cy="25" r="21" fill="none" stroke="#26303f" stroke-width="1"/>':''}<path d="M24 5 L44 40 L4 40 Z" fill="${fill}" stroke="#26303f" stroke-width="1.5"/>`,size),`${f.name}: ${flowLine(f)}. ${flowRankText(f)}`,()=>showStormFlow(id,f));}
  for(const [id,v] of Object.entries(s.wells||{})){const missing=v.change_ft==null||v.days_between==null||v.days_between>10;const fill=missing?'none':Math.abs(v.change_ft)<=0.25?'#fff':v.change_ft>0?`hsl(210 48% ${85-45*Math.min(3,v.change_ft)/3}%)`:`hsl(29 34% ${82-44*Math.min(3,-v.change_ft)/3}%)`;
    stormMarker([v.lat,v.lon],stormSymbol(`<path data-missing="${missing}" d="M24 7 L41 24 L24 41 L7 24 Z" fill="${fill}" stroke="#465063" stroke-width="1.5"/>`,22),`${v.name}: ${sn(v.change_ft)} ft from ${stormTime(v.before_at)} to ${stormTime(v.after_at)}`,()=>showStormWell(id,v));}
  for(const [id,l] of Object.entries(s.lakes||{})){if(!LAKE_LL[id])continue;stormMarker(LAKE_LL[id],stormSymbol(`<rect x="3" y="9" width="42" height="30" fill="#e7eef7" stroke="#294e76"/><text x="24" y="28" text-anchor="middle" font-size="11" fill="#26303f">${esc(l.change_ft==null?'?':(l.change_ft>0?'+':'')+sn(l.change_ft))}</text>`,38),`${id}: ${timed(l.elevation_t0,l.start_at,'ft')} → ${timed(l.elevation_now,l.now_at,'ft')}`,()=>showStormLake(id,l));}
  const unmapped=[];
  for(const [id,sp] of Object.entries(s.springs||{})){if(sp.lat==null||sp.lon==null){unmapped.push(id);continue;}const vals=[sp.start,sp.peak,sp.now];const max=Math.max(1,...vals.filter(v=>v!=null),sp.same_season_median||0);const bars=vals.map((v,i)=>`<rect x="${5+i*13}" y="${v==null?8:42-32*v/max}" width="9" height="${v==null?34:32*v/max}" fill="${v==null?'none':['#c7d9ed','#466f9c','#8baacd'][i]}" stroke="#294e76"/>`).join('');const y=42-32*(sp.same_season_median||0)/max;
    stormMarker([sp.lat,sp.lon],stormSymbol(bars+(sp.same_season_median==null?'':`<path d="M2 ${y} H45" stroke="#26303f" stroke-width="2"/>`),36),`${sp.name||id}: ${timed(sp.start,sp.readings.start?.at,'cfs')} → ${timed(sp.peak,sp.readings.peak?.at,'cfs')} → ${timed(sp.now,sp.readings.now?.at,'cfs')}`,()=>showStormSpring(id,sp));}
  $('#storm-unmapped').innerHTML=unmapped.length?`<span>Spring records without a verified map coordinate: </span>${unmapped.map(id=>`<button type="button" data-spring="${esc(id)}">${esc(id)}</button>`).join(' ')}`:'';
  for(const b of document.querySelectorAll('[data-spring]'))b.onclick=()=>showStormSpring(b.dataset.spring,s.springs[b.dataset.spring]);
  renderHypotheses(s);
}
function stormCard(title,body){card(`<p class="eyebrow">Storm measurements · ${esc(stormId)}</p><h2>${esc(title)}</h2>${body}<details><summary>Coverage and methods</summary>${(selectedStorm()?.caveats||[]).map(x=>`<p>${esc(x)}</p>`).join('')}<p><a href="../data/model/storms/${encodeURIComponent(stormId)}.json" target="_blank" rel="noopener">Read the window and its triggering readings</a></p></details>`);}
function showStormFlow(id,s){const rank=s.rank;const cat=s.nws_flood_category;const rules=Object.entries(s.response_thresholds||{}).map(([k,v])=>`<p><b>${esc(k)}:</b> ${esc(v)}</p>`).join('');const rise=Object.entries(s.rate_of_rise||{}).map(([k,v])=>v?`<p>${esc(sn(v.change_ft))} ft over ${esc(k.replace('_',' '))}: ${esc(timed(v.start.value,v.start.at,'ft'))} → ${esc(timed(v.end.value,v.end.at,'ft'))}.</p>`:'').join('');
  stormCard(s.name,`<p class="storm-reading">${esc(flowLine(s))}.</p><p>${s.baseline_gap_hours==null?"No timed baseline is available.":"Baseline precedes the window by "+esc(sn(s.baseline_gap_hours))+" hours. A long gap limits what the ratio establishes about this storm."}</p><p>Peak sampling: ${esc(s.peak_basis||'not recorded')}. ${esc(flowRankText(s))}</p>${rank?`<p>Peak is at percentile ${esc(sn(rank.percentile_of_daily_means))} against daily means from ${esc(rank.record_start)} through ${esc(rank.record_end)}. ${esc(rank.days_at_or_above)} days in ${esc(rank.years_at_or_above)} calendar years were at least this high; latest such day ${esc(rank.last_such_day||'none')}.</p>`:''}
  <p>${s.crossed===true?'Crossed':s.crossed===false?'No recorded crossing of':'No published'} its event threshold${s.threshold_cfs==null?'':` (${esc(sn(s.threshold_cfs))} cfs; ledger threshold for this window)`}. Peak/start ratio: ${esc(sn(s.ratio))}. Response: ${esc(s.response_class||'withheld; baseline or recession incomplete')}.</p>
  ${cat?`<p>NWS stage comparison at ${esc(stormTime(cat.peak.at))}: ${cat.category?`${esc(sn(cat.above_ft))} ft above the ${esc(cat.category)} threshold`:'below the published thresholds'}. Threshold source checked ${esc(stormTime(cat.thresholds_as_of))}.</p>`:`<p>${esc(s.nws_note)}</p>`}
  <p>Rain to peak: ${s.hours_rain_to_peak==null?'not established':esc(sn(s.hours_rain_to_peak))+' hours'}. ${esc(typeof s.rain_timing_note==='string'?s.rain_timing_note:`Gauge ${s.rain_timing_note.gauge}; first positive increment ${timed(s.rain_timing_note.onset.value,s.rain_timing_note.onset.at,'in')}. ${s.rain_timing_note.method}`)}</p><p>Peak to half: ${s.hours_peak_to_half==null?'not observed in the window':esc(sn(s.hours_peak_to_half))+' hours after '+esc(stormTime(s.peak_at))}.</p>${rise}<details><summary>Response thresholds and source readings</summary>${rules}<pre class="storm-source">${esc(JSON.stringify(s.readings,null,2))}</pre></details>`);}
function showStormRain(id,r){stormCard(r.name,`<p>${esc(timed(r.inches_window,r.observed_at,'in'))}. ${r.accumulation_field?`Operator field rainfall${esc(r.accumulation_field)} spans ${esc(stormTime(r.accumulation_start))} to ${esc(stormTime(r.observed_at))}; includes rain outside the storm.`:'No feed accumulation brackets this window.'}</p><p>30-day accumulation: ${esc(timed(r.inches_30d,r.observed_at,'in'))}.</p>${r.rain_rank?`<p>Position ${esc(r.rain_rank.rank_among_daily_totals)} against ${esc(r.rain_rank.days_on_record)} saved daily totals (${esc(r.rain_rank.record_start||'start unavailable')}–${esc(r.rain_rank.record_end||'end unavailable')}). The durations differ; this is not a daily rainfall record claim.</p>`:'<p>No comparable daily-rain history on file.</p>'}<p>${esc(r.intensity_note||'Hourly intensity not established from the available increments.')}</p><p class="storm-source">Source: ${esc(r.source_file)}</p>`);}
function showStormWell(id,w){stormCard(w.name,`<p>${esc(timed(w.level_before,w.before_at,'ft'))} → ${esc(timed(w.level_after,w.after_at,'ft'))}.</p><p>Change: ${esc(sn(w.change_ft))} ft over ${esc(sn(w.days_between))} days between those readings. ${esc(w.datum)}.</p><p>${esc([w.aquifer,w.zone,w.county].filter(Boolean).join(' · '))}</p>${w.days_between>10?'<p>Drawn hollow: readings are more than ten days apart.</p>':''}`);}
function showStormLake(id,l){const v=l.inflow;stormCard(id,`<p>${esc(timed(l.elevation_t0,l.start_at,'ft above mean sea level'))} → ${esc(timed(l.elevation_now,l.now_at,'ft above mean sea level'))}.</p><p>Change between those dates: ${esc(sn(l.change_ft))} ft. ${esc(timed(l.percent_full_now,l.percent_full_at,'% of conservation capacity'))}.</p>${v?`<p>Llano at Llano: ${esc(sn(v.acre_ft))} acre-feet passed the gauge from ${esc(stormTime(v.from_at))} through ${esc(stormTime(v.through_at))}. This is flow past the gauge, not a measurement of water added to Travis. ${esc(v.method)}.</p>`:''}<p>Lake comparison extends through the latest daily reading to show any lag after the storm.</p>`);}
function showStormSpring(id,s){const r=s.readings;stormCard(s.name||id,`<p>${esc(timed(s.start,r.start?.at,'cfs'))} → ${esc(timed(s.peak,r.peak?.at,'cfs'))} → ${esc(timed(s.now,r.now?.at,'cfs'))}.</p><p>Same-season median: ${esc(sn(s.same_season_median))} cfs, within 15 days of the window-end calendar date, across ${esc(s.record_start)}–${esc(s.record_end)}. Latest reading is at percentile ${esc(sn(s.percentile_of_record))} ${esc(s.comparison)}.</p>`);}
function renderHypotheses(s){const hs=s.hypotheses||[];$('#storm-hypothesis-list').innerHTML=hs.length?hs.map(h=>`<article class="storm-hypothesis"><b>Hypothesis · ${esc(h.status)}</b><p>${esc(h.text)}</p><p>${esc(h.evidence)}</p><p>Recorded ${esc(h.date)} · ${esc(h.initials)} · check by ${esc(h.check_by)}.</p></article>`).join(''):'<p>No hypotheses entered for this storm.</p>';}
